'use strict';

exports = module.exports = AccessControl;

/**
* @module Models
*/

/**
 * AccessControl manages the permissions of the current authenticator (see Controller#findAuthenticator) in the model controllers generated by the API module.
 *
 * You can set access control for create, read, update and delete actions on a model. For example, consider a User model and to control who may call POST /api/users to create a new user. The below example only allows admins to create new users:
 *
 * ```js
 * function User() {
 * 	this.email = [this.String, this.Authenticate];
 * 	this.admin = [this.Boolean];
 * 	this.accessControl = [this.CanCreate(function(authenticator) {
 * 		return (authenticator && authenticator.admin === true);
 * 	})];
 * }
 * app.model(User);
 * ```
 *
 * Please note the access control is only applied to the model controllers generated by the API. When calling any of the model methods directly no access control is applied. This is your responsibility.
 *
 * You can also set a key path to define the access control. If the authenticator matches the given key path, an action is permitted. For example, the below example only allows the author of the post to update the post.
 *
 * ```js
 * function Post() {
 * 	this.title = [this.String];
 * 	this.text = [this.String];
 * 	this.author = [this.BelongsTo(this.models.User)];
 * 	this.accessControl = [this.CanUpdate('author')];
 * }
 * app.model(Post);
 * ```
 *
 * You can also set Update on a property to configure who is allowed to change a property's value. See also PropertyTypes#Create, PropertyTypes#Read, PropertyTypes#Update, PropertyTypes#Delete for more information.
 *
 * @access private
 * @constructor
 */
function AccessControl() {
	this._ = {};
}

/**
 * Sets a permission function for the given action. The permission function is executed to evaluate if the access control for action is allowed.
 *
 * @param {create|read|update|delete} action             The access controlled action.
 * @param {Function(ModelInstance)} permissionFunction The function to allow or disallow the specific action. Returns truthy if allowed, and falsy if not allowed.
 */
AccessControl.prototype.setPermissionFunction = function(action, permissionFunction) {
	this._[action] = permissionFunction;
};

/**
 * Sets a key path to evaluate the access control. If the current authenticator matches the key path an action is allowed. Otherwise it's disallowed.
 *
 * Key path-based access control currently only works in update actions.
 *
 * @param {create|read|update|delete} action            The action.
 * @param {String} permissionKeyPath A key path
 */
AccessControl.prototype.setPermissionKeyPath = function(action, permissionKeyPath) {
	this._[action] = permissionKeyPath;
};

/**
 * Returns true if authenticator can create the model the access control belongs to.
 *
 * An example request in the model controllers would be:
 *
 * ```POST /api/users```
 *
 * @param {ModelInstance} authenticator The current authenticated authenticator (user). Can be null.
 * @return {Boolean}
 */
AccessControl.prototype.canCreate = function(authenticator) {
	var functionOrKeyPath = this._.create;

	if(typeof functionOrKeyPath == 'function') {
		return !!functionOrKeyPath(authenticator);
	}

	if(functionOrKeyPath) {
		// Ah key path is pretty difficult in create.
		throw new Error('Key path-based permission is not possible in create.');
	}

	if(!process.env.NODE_ENV || process.env.NODE_ENV == 'development') {
		console.log('Warning: no access control declared. In development environment access control will default to open, but in production the default will be closed to prevent security issues. To remove this warning, declare access control on your models.');
		return true;
	}

	return false;
};

/**
* Returns true if authenticator can read the model the access control belongs to.
*
* An example request in the model controllers would be:
*
* ```
* GET /api/users
* GET /api/users/1
* ```
*
* @param {ModelInstance} authenticator The current authenticated authenticator (user). Can be null.
* @return {Boolean}
*/
AccessControl.prototype.canRead = function(authenticator) {
	var functionOrKeyPath = this._.read;

	if(!functionOrKeyPath) {
		// No access control is declared. So let's fallback to true in development and false in production.

		if(!process.env.NODE_ENV || process.env.NODE_ENV == 'development') {
			console.log('Warning: no access control declared. In development environment access control will default to open, but in production the default will be closed to prevent security issues. To remove this warning, declare access control on your models.');
			return true;
		}

		// False in non-development mode.
		return false;
	}

	if(typeof functionOrKeyPath == 'function') {
		return !!functionOrKeyPath(authenticator);
	}

	return false;
};

/**
 * Returns the permission function for a specific action. The permission function can be executed to determine whether permission is allowed for the given access.
 *
 * In development mode, when no access control is set, this always allows all actions, but a warning is shown. In production mode, when no access control is set, the default behaviour is to always disallow any action.
 *
 * @param {create|read|update|delete} action The action.
 */
AccessControl.prototype.getPermissionFunction = function(action) {
	var functionOrKeyPath = this._[action];

	if(!functionOrKeyPath) {
		// No access control is declared. So let's fallback to true in development and false in production.

		if(!process.env.NODE_ENV || process.env.NODE_ENV == 'development') {
			console.log('Warning: no access control declared. In development environment access control will default to open, but in production the default will be closed to prevent security issues. To remove this warning, declare access control on your models.');
			return function() { return true; };
		}

		// False in non-development mode.
		return function() { return false; };
	}

	if(typeof functionOrKeyPath != 'function') {
		// A key path is defined, so we'll allow this.

		// TODO: If it's not a function, it does not have to be a string.
		return function() { return true; };
	}

	return functionOrKeyPath;
};

/**
 * Returns the key path set for the given action, or null if a permission function is set. The system requesting the key path is responsbile for whether the key path matches the authenticated authenticator.
 *
 * @param {create|read|update|delete} action The action.
 */
AccessControl.prototype.getPermissionKeyPath = function(action) {
	var functionOrKeyPath = this._[action];

	if(typeof functionOrKeyPath != 'string') {
		return null;
	}

	return functionOrKeyPath;
};
